# Generated by Django 5.2.14 on 2026-05-25 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_blogpost"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="blogpost",
            new_name="api_blogpos_status_967e3c_idx",
            old_name="api_blogpos_status_8a1f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="blogpost",
            new_name="api_blogpos_categor_83b24e_idx",
            old_name="api_blogpos_categor_4e8b1a_idx",
        ),
        migrations.RenameIndex(
            model_name="blogpost",
            new_name="api_blogpos_is_feat_754d2d_idx",
            old_name="api_blogpos_is_feat_2c9d4e_idx",
        ),
    ]
